# Generated by Django 3.0.3 on 2020-08-07 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('published', models.DateTimeField()),
                ('eyeWidth', models.IntegerField(default=50)),
                ('eyeHeight', models.IntegerField(default=50)),
                ('happiness', models.IntegerField(default=50)),
                ('smileWidth', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Face')),
            ],
        ),
    ]
